version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/root/HomeworkAggregator
    command: ["./run-app"]
    ports:
      - "8888:8888"
    environment:
      - POSTGRES_USER=team28
      - POSTGRES_PASSWORD=team28password
      - POSTGRES_DB=hwuserinfo
      - POSTGRES_HOST=homeworkaggregator_db
      - POSTGRES_PORT=5432   
      - GITHUB_CLIENT_ID=14bda77f480ab19d7bbf
      - GITHUB_CLIENT_SECRET=d32a058922985c50b03b20724f7f7000d0bf0853
      - SUPABASE_DB=gM5Z7Lib1XL5afgf
      - PRODUCTION=false

  db:
    image: postgres
    container_name: homeworkaggregator_db
    environment:
      POSTGRES_USER: team28
      POSTGRES_PASSWORD: team28password
      POSTGRES_DB: hwuserinfo
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: