#!/bin/bash

# Activate the virtual environment (if you're using one)
source /root/.venv/bin/activate

# Set environment variables (if needed)
export FLASK_APP=app.py
export FLASK_ENV=development  # Use 'production' in a production environment

# Start the Flask application
flask run --host=0.0.0.0 --port=8888